### ISSUE TITLE
按照文档的步骤实现不了和官网一样的markdown功能

### ISSUE THREAD

**Issue by Neaton** [mycolorway/simditor-livemd#1]
官网效果如图：
![image](https://cloud.githubusercontent.com/assets/453953/3536443/eac9fa6a-0811-11e4-9c46-c42b1792e24f.png)
我的代码如图：
![image](https://cloud.githubusercontent.com/assets/453953/3536515/c4bd1400-0812-11e4-9694-e5f5f70977aa.png)
我的运行结果如图：
![image](https://cloud.githubusercontent.com/assets/453953/3536524/dd7fc0f0-0812-11e4-9ada-f4bdc88cebfc.png)

**Comment by RuochenLyu** [comment]
Tower Markdown 文档并不是用这个插件实现的（是基于 https://github.com/chjj/marked 开发的）。

这个插件实现的是通过 Markdown 语法进行快速输入，比如输入：`*` 在按空格就会新建一个无序列表。
基本都是通过空格和回车来出发的，Tower 的讨论和普通文档都支持这种形式。

**Comment by Neaton** [comment]
非常感谢～～
