### ISSUE TITLE
这个感觉没啥用呢？

### ISSUE THREAD

**Issue by niefufeng** [mycolorway/simditor-livemd#4]
我引入了，但是和没引入一样。
输入以下代码：

``` php
function func($params){
    echo 233;
}
```

还是启动的编辑器那个代码插入，输入**加粗**也没有效果，是不是我姿势不对？

**Comment by RuochenLyu** [comment]
这个是这样实现的：输入 `>` 然后按空格就会插入一个引用，输入 ``` 按空格就会插入一个代码块。
可以在 [tower.im](https://tower.im) 的编辑器里测试看看。

**Comment by niefufeng** [comment]
我试了，比如要加粗，必须先输入*\* **，然后再在中间输入文字。如果先输入**，然后输入文字，再输入**，会原样输出。
P.S.:在 [tower](http://www.tower.im) 上面测试的

**Comment by RuochenLyu** [comment]
我这里没问题呀，你看下我录屏了。
![test](https://cloud.githubusercontent.com/assets/1207465/4975894/155a0d16-6919-11e4-9572-f7b72058ac3f.gif)

**Comment by niefufeng** [comment]
恩，按照你录屏的方法，可以啦，三克油！
弱弱的说下，还是有很多语法不支持，比如：

> `我是文字高亮`:关键词高亮
> `代码高亮(着色)`:simditor代码为一个颜色(黑色)
> `代码排版`:我在输入时即使用了换行和空格，代码在显示时也会变成一行！
> `表格`:↓
> `h1~h6`:h1~h6其实也挺有用的
> `more...`

| Item | Value | Qty |
| :-- | --: | :-: |
| Computer | 1600 USD | 5 |
| Phone | 12 USD | 12 |
| Pipe | 1 USD | 234 |

> 印象笔记有款第三方markdown插件不错，叫`马克飞象`，作者可以参考下

最后，感谢不厌其烦的看完了，开源项目不容易，感谢作者的付出^_^！

**Comment by RuochenLyu** [comment]
这个组件只是为了用 Markdown 语法来实现些快速输入的操作，并不是为了做成一个 Markdown 编辑器。
标题的问题是因为 Tower 评论区不支持标题，所以不能插入，Tower 文档是可以插入标题的。
表格并不是 Markdown 规范里的。
代码高亮和 Markdown 也关系不大，Tower 是用 https://highlightjs.org/ 实现的。
